apiVersion: v2
name: samaritan
version: 0.1.0-alpha
kubeVersion: v1.18-0 - 1.20-0
description: Platform to collect and analyze vulnerability discovery metrics.
type: application
home: https://samaritan.works/
sources:
  - https://github.com/samaritan
dependencies:
  - name: common
    version: ~1.4.1
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Nuthan Munaiah
    email: nuthan.munaiah@securedecisions.com
    url: https://nuthanmunaiah.github.io/
