{{- if eq .Values.storage.provider "efs" }}
---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: efs.csi.aws.com
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  attachRequired: false
{{- end }}
