---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-repositories
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  {{- if eq .Values.storage.provider "local" }}
  storageClassName: sc-local
  hostPath:
    path: "{{ clean .Values.storage.providers.local.root }}/repositories"
  {{- else if eq .Values.storage.provider "efs" }}
  storageClassName: sc-efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.providers.efs.fileSystemId }}
  {{- end }}
{{- if not .Values.rabbitmq.external }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  {{- if eq .Values.storage.provider "local" }}
  storageClassName: sc-local
  hostPath:
    path: "{{ clean .Values.storage.providers.local.root }}/rabbitmq"
  {{- else if eq .Values.storage.provider "efs" }}
  storageClassName: sc-efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.providers.efs.fileSystemId }}
  {{- end }}
{{- end }}
{{- if not .Values.mysql.external }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  {{- if eq .Values.storage.provider "local" }}
  storageClassName: sc-local
  hostPath:
    path: "{{ clean .Values.storage.providers.local.root }}/mysql"
  {{- else if eq .Values.storage.provider "efs" }}
  storageClassName: sc-efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.providers.efs.fileSystemId }}
  {{- end }}
{{- end }}
