---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-repositories
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if eq .Values.storage.provider "local" }}
  storageClassName: sc-local
  {{- else if eq .Values.storage.provider "efs" }}
  storageClassName: sc-efs
  {{- end }}
  volumeName: pv-repositories
  resources:
    requests:
      storage: 1Gi
{{- if not .Values.rabbitmq.external }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if eq .Values.storage.provider "local" }}
  storageClassName: sc-local
  {{- else if eq .Values.storage.provider "efs" }}
  storageClassName: sc-efs
  {{- end }}
  volumeName: pv-rabbitmq
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- if not .Values.mysql.external }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if eq .Values.storage.provider "local" }}
  storageClassName: sc-local
  {{- else if eq .Values.storage.provider "efs" }}
  storageClassName: sc-efs
  {{- end }}
  volumeName: pv-mysql
  resources:
    requests:
      storage: 1Gi
{{- end }}
