apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret
stringData:
  mysql.user: {{ .Values.mysql.application.user | quote }}
  mysql.password: {{ required "MySQL application password must be provided." .Values.mysql.application.password | quote}}
  mysql.root_password: {{ required "MySQL root password must be provided." .Values.mysql.root.password | quote }}
  rabbitmq.default_user: {{ .Values.rabbitmq.user | quote }}
  rabbitmq.default_pass: {{ required "RabbitMQ default password must be provided." .Values.rabbitmq.password | quote }}
  redis.password: {{ .Values.redis.password | quote }}
