apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret
  namespace: {{ .Release.Namespace | quote }}
stringData:
  mysql.user: {{ .Values.mysql.application.user | quote }}
  mysql.password: {{ required "`mysql.application.password` must be set in values.yaml or with --set" .Values.mysql.application.password | quote}}
  mysql.root_password: {{ required "`mysql.root.password` must be set in values.yaml or with --set" .Values.mysql.root.password | quote }}
  rabbitmq.default_user: {{ .Values.rabbitmq.user | quote }}
  rabbitmq.default_pass: {{ required "`rabbitmq.password` must be set in values.yaml or with --set" .Values.rabbitmq.password | quote }}
  redis.password: {{ required "`redis.password` must be set in values.yaml or with --set" .Values.redis.password | quote }}
