---
kind: StorageClass
apiVersion: storage.k8s.io/v1
{{- if eq .Values.storage.provider "local" }}
metadata:
  name: sc-local
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
provisioner: kubernetes.io/no-provisioner
{{- else if eq .Values.storage.provider "efs" }}
metadata:
  name: sc-efs
provisioner: efs.csi.aws.com
{{- end }}
